name: "o5ui"

deploymentConfig:
  quickMode: true

runtimes:
  - name: main
    routes:
      - prefix: "/"
        protocol: ROUTE_PROTOCOL_HTTP
        subdomains: [o5]
        bypass_ingress: true
        port: 80
        route_group: ROUTE_GROUP_FALLBACK
    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
          name: o5-ui
          registry: ghcr.io/pentops
